[package]
edition = "2021"
name = "vm-agent"
version = "0.0.3-dev"

[dependencies]
env_logger = "0.9"
libudev = "0.3"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
config = { version = "0.12"}
